epos4_controller_node:
  ros__parameters:
    tread_width: 0.41 #[m]
    tire_diam: 0.15   #[m]
    gear_ratio: 0.2   #motor_rev / wheel_rev
    invert_left: true
    invert_right: true

epos4_odometry_node:
  ros__parameters:
    tread_width: 0.41 #[m]
    tire_diam: 0.15   #[m]
    gear_ratio: 0.2   #motor_rev / wheel_rev
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_tf: true
    invert_left: true
    invert_right: true